-- MySQL Script generated by MySQL Workbench
-- Tue May  6 22:35:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Train_Station
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Train_Station` ;

-- -----------------------------------------------------
-- Schema Train_Station
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Train_Station` DEFAULT CHARACTER SET utf8mb4 ;
USE `Train_Station` ;

-- -----------------------------------------------------
-- Table `Train_Station`.`Stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Stations` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Stations` (
  `station_id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`station_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Teams` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Teams` (
  `team_id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `team_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`team_id`),
  INDEX `department_id_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `team_department_id`
    FOREIGN KEY (`department_id`)
    REFERENCES `Train_Station`.`Departments` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Employees` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(40) NOT NULL,
  `last_name` VARCHAR(40) NOT NULL,
  `patronymic` VARCHAR(40) NULL,
  `post` VARCHAR(130) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `standard_salary` INT NOT NULL,
  `team_id` INT NOT NULL,
  `registered` DATETIME NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `employees_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `Train_Station`.`Teams` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Departments` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Departments` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `department_type` ENUM('Отдел машинистов', 'Отдел деспетчеров', 'Отдел ремонтников', 'Отдел путейцев', 'Отдел кассиров', 'Отдел гражданской службы', 'Отдел справочной службы') NOT NULL,
  `station_id` INT NOT NULL,
  `administrator_id` INT NOT NULL,
  PRIMARY KEY (`department_id`),
  INDEX `station_id_idx` (`station_id` ASC) VISIBLE,
  INDEX `administrator_departments_employees_fk_idx` (`administrator_id` ASC) VISIBLE,
  CONSTRAINT `department_station_id`
    FOREIGN KEY (`station_id`)
    REFERENCES `Train_Station`.`Stations` (`station_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `administrator_departments_employees_fk`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `Train_Station`.`Employees` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Medical_examinations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Medical_examinations` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Medical_examinations` (
  `medical_examination_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `medical_examination` VARCHAR(500) NOT NULL,
  `date` DATE NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`medical_examination_id`),
  INDEX `employee_id_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `medical_employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Train_Station`.`Employees` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Locomotives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Locomotives` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Locomotives` (
  `locomotive_id` INT NOT NULL AUTO_INCREMENT,
  `locomotive_crew_id` INT NOT NULL,
  `locomotive_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`locomotive_id`),
  INDEX `locomotive_teams_fk_idx` (`locomotive_crew_id` ASC) VISIBLE,
  CONSTRAINT `locomotives_teams_fk`
    FOREIGN KEY (`locomotive_crew_id`)
    REFERENCES `Train_Station`.`Teams` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Trains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Trains` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Trains` (
  `train_id` INT NOT NULL AUTO_INCREMENT,
  `civil_service_team_id` INT NOT NULL,
  `locomotive_id` INT NOT NULL,
  `train_type` ENUM('Скорый', 'Пассажирский') NOT NULL,
  `carriage_number` INT NOT NULL,
  PRIMARY KEY (`train_id`),
  INDEX `teams_fk_idx` (`civil_service_team_id` ASC) VISIBLE,
  INDEX `locomotives_fk_idx` (`locomotive_id` ASC) VISIBLE,
  CONSTRAINT `trains_teams_fk`
    FOREIGN KEY (`civil_service_team_id`)
    REFERENCES `Train_Station`.`Teams` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `trains_locomotives_fk`
    FOREIGN KEY (`locomotive_id`)
    REFERENCES `Train_Station`.`Locomotives` (`locomotive_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Schedule` (
  `flight_id` INT NOT NULL AUTO_INCREMENT,
  `category` ENUM('Внутренний', 'Международный', 'Туристический', 'Специальный') NOT NULL,
  `train_id` INT NOT NULL,
  `train_name` VARCHAR(45) NOT NULL,
  `ticket_price` INT NOT NULL,
  PRIMARY KEY (`flight_id`),
  INDEX `train_id_idx` (`train_id` ASC) VISIBLE,
  CONSTRAINT `schedule_train_id`
    FOREIGN KEY (`train_id`)
    REFERENCES `Train_Station`.`Trains` (`train_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Passengers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Passengers` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Passengers` (
  `passenger_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `patronymic` VARCHAR(30) NULL,
  `sex` TINYINT(1) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `registered` DATE NOT NULL,
  PRIMARY KEY (`passenger_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Tickets` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Tickets` (
  `ticket_id` INT NOT NULL AUTO_INCREMENT,
  `luggage` TINYINT(1) NOT NULL,
  `passenger_id` INT NOT NULL,
  `status` ENUM('Куплен', 'Возвращён', 'Использован', 'Истёк') NOT NULL,
  `flight_id` INT NOT NULL,
  `sell_date` DATETIME NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `flight_id_idx` (`flight_id` ASC) VISIBLE,
  INDEX `passenger_id_idx` (`passenger_id` ASC) VISIBLE,
  CONSTRAINT `tickets_flight_id`
    FOREIGN KEY (`flight_id`)
    REFERENCES `Train_Station`.`Schedule` (`flight_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tickets_passenger_id`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `Train_Station`.`Passengers` (`passenger_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Salary` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Salary` (
  `salary_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `amount` INT NOT NULL,
  `optional_explanation` VARCHAR(45) NULL,
  PRIMARY KEY (`salary_id`),
  INDEX `salary_employees_fk_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `salary_employees_fk`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Train_Station`.`Employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Repair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Repair` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Repair` (
  `repair_id` INT NOT NULL AUTO_INCREMENT,
  `locomotive_id` INT NOT NULL,
  `repair_team_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `cost` INT NOT NULL,
  `repair` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`repair_id`),
  INDEX `repair_locomotives_fk_idx` (`locomotive_id` ASC) VISIBLE,
  INDEX `repair_teams_fk_idx` (`repair_team_id` ASC) VISIBLE,
  CONSTRAINT `repair_locomotives_fk`
    FOREIGN KEY (`locomotive_id`)
    REFERENCES `Train_Station`.`Locomotives` (`locomotive_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `repair_teams_fk`
    FOREIGN KEY (`repair_team_id`)
    REFERENCES `Train_Station`.`Teams` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Routes` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Routes` (
  `stop_id` INT NOT NULL AUTO_INCREMENT,
  `station_id` INT NOT NULL,
  `arrival` DATETIME NOT NULL,
  `departure` DATETIME NOT NULL,
  `stop_type` ENUM('Начало', 'Остановка', 'Конец') NOT NULL,
  `flight_id` INT NOT NULL,
  PRIMARY KEY (`stop_id`),
  INDEX `route_fk_idx` (`flight_id` ASC) VISIBLE,
  INDEX `station_fk_idx` (`station_id` ASC) VISIBLE,
  CONSTRAINT `route_schedule_fk`
    FOREIGN KEY (`flight_id`)
    REFERENCES `Train_Station`.`Schedule` (`flight_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `route_station_fk`
    FOREIGN KEY (`station_id`)
    REFERENCES `Train_Station`.`Stations` (`station_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train_Station`.`Inspection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train_Station`.`Inspection` ;

CREATE TABLE IF NOT EXISTS `Train_Station`.`Inspection` (
  `inspection_id` INT NOT NULL AUTO_INCREMENT,
  `inspection_type` ENUM('плановый', 'рейсовый') NOT NULL,
  `result` VARCHAR(450) NOT NULL,
  `locomotive_id` INT NOT NULL,
  `datetime` DATETIME NOT NULL,
  PRIMARY KEY (`inspection_id`),
  INDEX `locomotives_fk_idx` (`locomotive_id` ASC) VISIBLE,
  CONSTRAINT `inspections_locomotives_fk`
    FOREIGN KEY (`locomotive_id`)
    REFERENCES `Train_Station`.`Locomotives` (`locomotive_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
