USE train_station;
SELECT * FROM stations;
SELECT SLEEP(1);
SELECT * FROM passengers;
SELECT SLEEP(1);
SELECT * FROM administration;
SELECT SLEEP(1);
SELECT * FROM departments;
SELECT SLEEP(1);
SELECT * FROM teams;
SELECT SLEEP(1);
SELECT * FROM locomotives;
SELECT SLEEP(1);
SELECT * FROM employees;
SELECT SLEEP(1);
SELECT * FROM Medical_examinations;
SELECT SLEEP(1);
SELECT * FROM Trains;
SELECT SLEEP(1);
SELECT * FROM tickets;
SELECT SLEEP(1);
SELECT * FROM schedule;
