-- MySQL Script generated by MySQL Workbench
-- Fri Sep 13 20:48:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema transportation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema transportation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transportation` DEFAULT CHARACTER SET utf8 ;
USE `transportation` ;

-- -----------------------------------------------------
-- Table `transportation`.`drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transportation`.`drivers` (
  `driver_id` INT NOT NULL AUTO_INCREMENT,
  `family` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `license_id` INT NOT NULL,
  PRIMARY KEY (`driver_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transportation`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transportation`.`cars` (
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `number` VARCHAR(9) NOT NULL,
  `year` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`car_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transportation`.`accident`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transportation`.`accident` (
  `accident_id` INT NOT NULL AUTO_INCREMENT,
  `car_id` INT NOT NULL,
  `driver_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`accident_id`),
  INDEX `driver_id_idx` (`driver_id` ASC) VISIBLE,
  INDEX `car_id_idx` (`car_id` ASC) VISIBLE,
  CONSTRAINT `driver_id`
    FOREIGN KEY (`driver_id`)
    REFERENCES `transportation`.`drivers` (`driver_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `car_id`
    FOREIGN KEY (`car_id`)
    REFERENCES `transportation`.`cars` (`car_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
