-- MySQL Script generated by MySQL Workbench
-- Tue Oct  1 16:41:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TrainStation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrainStation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrainStation` DEFAULT CHARACTER SET utf8mb4 ;
USE `TrainStation` ;

-- -----------------------------------------------------
-- Table `TrainStation`.`Stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainStation`.`Stations` (
  `station_id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`station_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainStation`.`Teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainStation`.`Teams` (
  `team_id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`team_id`),
  INDEX `department_id_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `team_department_id`
    FOREIGN KEY (`department_id`)
    REFERENCES `TrainStation`.`Departments` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainStation`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainStation`.`Employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `full name` VARCHAR(130) NOT NULL,
  `post` VARCHAR(130) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `employees_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `TrainStation`.`Teams` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainStation`.`Adimnistration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainStation`.`Adimnistration` (
  `administrator_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`administrator_id`),
  INDEX `fk_Adimnistration_Employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Adimnistration_Employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `TrainStation`.`Employees` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainStation`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainStation`.`Departments` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(45) NOT NULL,
  `station_id` INT NOT NULL,
  `administrator_id` INT NOT NULL,
  PRIMARY KEY (`department_id`),
  INDEX `station_id_idx` (`station_id` ASC) VISIBLE,
  INDEX `fk_Departments_Adimnistration1_idx` (`administrator_id` ASC) VISIBLE,
  CONSTRAINT `department_station_id`
    FOREIGN KEY (`station_id`)
    REFERENCES `TrainStation`.`Stations` (`station_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Departments_Adimnistration1`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `TrainStation`.`Adimnistration` (`administrator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainStation`.`Medical_examinations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainStation`.`Medical_examinations` (
  `medical_examination_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `medical_examination` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`medical_examination_id`),
  INDEX `employee_id_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `medical_employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `TrainStation`.`Employees` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainStation`.`Locomotives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainStation`.`Locomotives` (
  `locomotive_id` INT NOT NULL AUTO_INCREMENT,
  `repair_team_id` INT NOT NULL,
  `repair` VARCHAR(500) NOT NULL,
  `regular_inspection` DATETIME NOT NULL,
  `scheduled_inspection` DATETIME NOT NULL,
  `maintenance` DATETIME NOT NULL,
  `locomotive_crew_id` INT NOT NULL,
  PRIMARY KEY (`locomotive_id`),
  INDEX `team_id_idx` (`repair_team_id` ASC) VISIBLE,
  INDEX `fk_Locomotives_Teams1_idx` (`locomotive_crew_id` ASC) VISIBLE,
  CONSTRAINT `locomotive_team_id`
    FOREIGN KEY (`repair_team_id`)
    REFERENCES `TrainStation`.`Teams` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Locomotives_Teams1`
    FOREIGN KEY (`locomotive_crew_id`)
    REFERENCES `TrainStation`.`Teams` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainStation`.`Trains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainStation`.`Trains` (
  `train_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `train_number` VARCHAR(45) NOT NULL,
  `repair_team_id` INT NOT NULL,
  `civil_service_team_id` INT NOT NULL,
  `locomotive_id` INT NOT NULL,
  PRIMARY KEY (`train_id`),
  INDEX `repair_team_id_idx` (`repair_team_id` ASC) VISIBLE,
  INDEX `fk_Trains_Locomotives1_idx` (`locomotive_id` ASC) VISIBLE,
  INDEX `civil_service_team_id_idx` (`civil_service_team_id` ASC) VISIBLE,
  CONSTRAINT `trains_repair_team_id`
    FOREIGN KEY (`repair_team_id`)
    REFERENCES `TrainStation`.`Teams` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trains_Locomotives1`
    FOREIGN KEY (`locomotive_id`)
    REFERENCES `TrainStation`.`Locomotives` (`locomotive_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `trains_civil_service_team_id`
    FOREIGN KEY (`civil_service_team_id`)
    REFERENCES `TrainStation`.`Teams` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainStation`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainStation`.`Schedule` (
  `flight_id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `administrator_id` INT NOT NULL,
  `departure` DATETIME NOT NULL,
  `arrival` DATETIME NOT NULL,
  `train_id` INT NOT NULL,
  `route` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`flight_id`),
  INDEX `administrator_id_idx` (`administrator_id` ASC) VISIBLE,
  INDEX `train_id_idx` (`train_id` ASC) VISIBLE,
  CONSTRAINT `schedule_administrator_id`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `TrainStation`.`Adimnistration` (`administrator_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `schedule_train_id`
    FOREIGN KEY (`train_id`)
    REFERENCES `TrainStation`.`Trains` (`train_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainStation`.`Passengers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainStation`.`Passengers` (
  `passenger_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`passenger_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainStation`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainStation`.`Tickets` (
  `ticket_id` INT NOT NULL AUTO_INCREMENT,
  `luggage` TINYINT(1) NOT NULL,
  `passenger_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `flight_id` INT NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `flight_id_idx` (`flight_id` ASC) VISIBLE,
  INDEX `passenger_id_idx` (`passenger_id` ASC) VISIBLE,
  CONSTRAINT `tickets_flight_id`
    FOREIGN KEY (`flight_id`)
    REFERENCES `TrainStation`.`Schedule` (`flight_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tickets_passenger_id`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `TrainStation`.`Passengers` (`passenger_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
